import type { ConversionFormat, ConversionPreset } from "@/types"

export const CONVERSION_FORMATS: ConversionFormat[] = [
  // Document Formats
  {
    id: "docx",
    name: "Microsoft Word",
    extension: ".docx",
    icon: "📄",
    description: "Best for text-heavy documents with formatting",
    category: "document",
    settings: {
      preserveFonts: true,
      quality: "high",
    },
    recommendationLevel: "recommended",
    suitableFor: ["text", "mixed"],
    tooltip: "Perfect for documents with text, paragraphs, and formatting. Maintains layout and fonts.",
  },
  {
    id: "txt",
    name: "Plain Text",
    extension: ".txt",
    icon: "📃",
    description: "Simple text extraction without formatting",
    category: "document",
    recommendationLevel: "recommended",
    suitableFor: ["text"],
    tooltip: "Extracts only text content. Good for simple documents without formatting needs.",
  },
  {
    id: "rtf",
    name: "Rich Text Format",
    extension: ".rtf",
    icon: "📝",
    description: "Universal rich text format",
    category: "document",
    recommendationLevel: "caution",
    suitableFor: ["text"],
    tooltip: "Compatible with most word processors. May lose some advanced formatting.",
  },
  {
    id: "xlsx",
    name: "Microsoft Excel",
    extension: ".xlsx",
    icon: "📊",
    description: "Perfect for tables and structured data",
    category: "document",
    settings: {
      extractTables: true,
      quality: "high",
    },
    recommendationLevel: "recommended",
    suitableFor: ["table", "mixed"],
    tooltip: "Ideal for PDFs with tables, spreadsheets, and data. Preserves table structure.",
  },
  {
    id: "csv",
    name: "CSV",
    extension: ".csv",
    icon: "📋",
    description: "Simple table data format",
    category: "data",
    recommendationLevel: "recommended",
    suitableFor: ["table"],
    tooltip: "Best for simple table data. Compatible with Excel and databases.",
  },
  {
    id: "odt",
    name: "OpenDocument Text",
    extension: ".odt",
    icon: "📄",
    description: "Open source document format",
    category: "document",
    recommendationLevel: "caution",
    suitableFor: ["text"],
    tooltip: "Open source alternative to Word. Good compatibility but less common.",
  },
  {
    id: "html",
    name: "HTML",
    extension: ".html",
    icon: "🌐",
    description: "Web page format with links",
    category: "document",
    recommendationLevel: "caution",
    suitableFor: ["text", "mixed"],
    tooltip: "Good for web publishing. May require cleanup for complex layouts.",
  },
  {
    id: "epub",
    name: "EPUB",
    extension: ".epub",
    icon: "📚",
    description: "E-book format for reading devices",
    category: "document",
    recommendationLevel: "caution",
    suitableFor: ["text"],
    tooltip: "Perfect for e-readers. Best for text-heavy documents without complex layouts.",
  },

  // Image Formats
  {
    id: "jpg",
    name: "JPEG",
    extension: ".jpg",
    icon: "🖼️",
    description: "High quality photos and images",
    category: "image",
    settings: {
      quality: "high",
      dpi: 300,
      compression: "medium",
    },
    recommendationLevel: "recommended",
    suitableFor: ["image", "mixed"],
    tooltip: "Best for photos and colorful images. Good compression with quality balance.",
  },
  {
    id: "png",
    name: "PNG",
    extension: ".png",
    icon: "🖼️",
    description: "Lossless images with transparency",
    category: "image",
    settings: {
      quality: "maximum",
      dpi: 300,
      compression: "none",
    },
    recommendationLevel: "recommended",
    suitableFor: ["image", "mixed"],
    tooltip: "Perfect for images with text, logos, or transparency. No quality loss.",
  },
  {
    id: "tiff",
    name: "TIFF",
    extension: ".tiff",
    icon: "🖼️",
    description: "Professional high-quality images",
    category: "image",
    recommendationLevel: "recommended",
    suitableFor: ["image"],
    tooltip: "Professional format for high-quality images. Large file sizes but maximum quality.",
  },
  {
    id: "bmp",
    name: "BMP",
    extension: ".bmp",
    icon: "🖼️",
    description: "Uncompressed bitmap images",
    category: "image",
    recommendationLevel: "caution",
    suitableFor: ["image"],
    tooltip: "Uncompressed format. Very large files but perfect quality.",
  },

  // Other Formats
  {
    id: "md",
    name: "Markdown",
    extension: ".md",
    icon: "📝",
    description: "Formatted text markup for developers",
    category: "other",
    recommendationLevel: "caution",
    suitableFor: ["text"],
    tooltip: "Great for developers and technical documentation. Simple formatting syntax.",
  },
]

export const CONVERSION_PRESETS: ConversionPreset[] = [
  {
    id: "best-quality",
    name: "Best Quality",
    description: "Maximum fidelity, larger file size",
    settings: {
      quality: "maximum",
      dpi: 600,
      compression: "none",
      preserveFonts: true,
    },
  },
  {
    id: "balanced",
    name: "Balanced",
    description: "Good quality, reasonable size",
    settings: {
      quality: "high",
      dpi: 300,
      compression: "low",
      preserveFonts: true,
    },
  },
  {
    id: "fast",
    name: "Fast",
    description: "Quick conversion, basic quality",
    settings: {
      quality: "medium",
      dpi: 150,
      compression: "medium",
      preserveFonts: false,
    },
  },
  {
    id: "mobile",
    name: "Mobile Optimized",
    description: "Optimized for mobile viewing",
    settings: {
      quality: "medium",
      dpi: 200,
      compression: "high",
      preserveFonts: false,
    },
  },
]
